name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  test-contracts:
    name: Test Smart Contracts
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for contracts
        id: check-contracts
        run: |
          if [ -n "$(find contracts -name '*.sol' 2>/dev/null)" ]; then
            echo "has_contracts=true" >> $GITHUB_OUTPUT
          else
            echo "has_contracts=false" >> $GITHUB_OUTPUT
            echo "No Solidity contracts found - running basic tests only"
          fi

      - name: Compile contracts
        if: steps.check-contracts.outputs.has_contracts == 'true'
        run: npx hardhat compile

      - name: Run contract tests
        run: npx hardhat test

